import { destinationImageWidths, brandImageWidths } from '../data/imageManifest';

/**
 * Turns a photo's name into the attributes for a responsive <img>.
 *
 * The site keeps each photo as several WebP widths (generated by
 * scripts/optimize-images.cjs from the originals in source-images/); the
 * browser picks the smallest one that is sharp enough for the size it
 * draws the photo at (`sizes`) and the screen's pixel density. Which
 * widths exist is recorded in data/imageManifest.js.
 */

function build(dir, name, widths) {
  // A mid-size file is the fallback `src` for anything that ignores srcset.
  const fallback = widths.find((w) => w >= 720) ?? widths[widths.length - 1];
  return {
    src: `${dir}/${name}-${fallback}.webp`,
    srcSet: widths.map((w) => `${dir}/${name}-${w}.webp ${w}w`).join(', '),
  };
}

/**
 * @param {string} src - the destination's logical photo path,
 *   "/images/destinations/<slug>.png" (see data/destinationCatalogue.js).
 * @returns {{src: string, srcSet?: string}} — for a slug with no generated
 *   photo, the path unchanged (it 404s, and DestinationImage then shows its
 *   neutral placeholder as before).
 */
export function destinationPhoto(src) {
  const match = /^\/images\/destinations\/([a-z0-9-]+)\.png$/.exec(src ?? '');
  const widths = match ? destinationImageWidths[match[1]] : undefined;
  return widths ? build('/images/destinations', match[1], widths) : { src };
}

/** @param {'laxman'|'contact'} name */
export function brandPhoto(name) {
  return build('/images/brand', name, brandImageWidths[name]);
}
