/**
 * Builds the responsive WebP photos the site serves, from the original PNGs
 * kept in source-images/ (not deployed).
 *
 *   source-images/destinations/<slug>.png  ->  public/images/destinations/<slug>-<width>.webp
 *   source-images/brand/{laxman,contact}.png -> public/images/brand/<name>-<width>.webp
 *
 * Several widths per photo are written so phones download a small file and
 * large/retina screens a bigger one (the site picks with srcset/sizes; see
 * src/utils/photoSources.js). Widths never exceed the original's own width.
 * It also writes src/data/imageManifest.js (which widths exist for each
 * photo) and reports, for every photo, the SSIM quality score against the
 * original (1.0 = identical) so a bad encode can't slip through.
 *
 * To add or replace a photo: put the original PNG in source-images/, then
 *
 *   npm install --no-save ffmpeg-static     # a one-off tool, not a dependency
 *   npm run images
 */
const fs = require('fs');
const path = require('path');
const cp = require('child_process');

const FF = require('ffmpeg-static');
const ROOT = path.resolve(__dirname, '..');
// Lowest quality that still keeps each photo at or above MIN_SSIM vs its original.
const QUALITY_STEPS = [78, 84, 90];
const DESTINATION_WIDTHS = [480, 720, 960, 1280];
const BRAND_WIDTHS = { laxman: [640, 960, 1280, 1680], contact: [480, 720, 960, 1280] };
const MIN_SSIM = 0.97;

function pngSize(file) {
  const b = fs.readFileSync(file);
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
}

function widthsFor(native, targets) {
  const below = targets.filter((w) => w < native);
  const top = Math.min(native, targets[targets.length - 1]);
  return [...new Set([...below, top])].sort((a, b) => a - b);
}

function encode(src, out, width, quality) {
  cp.execFileSync(FF, ['-y', '-v', 'error', '-i', src, '-vf', `scale=${width}:-2:flags=lanczos`, '-c:v', 'libwebp', '-quality', String(quality), '-compression_level', '5', out]);
}

function ssim(src, out, width) {
  const r = cp.spawnSync(FF, ['-hide_banner', '-i', out, '-i', src, '-lavfi', `[1]scale=${width}:-2:flags=lanczos[r];[0][r]ssim`, '-f', 'null', '-'], { encoding: 'utf8' });
  const m = /All:([0-9.]+)/.exec(r.stderr || '');
  return m ? Number(m[1]) : NaN;
}

const manifest = { destinations: {}, brand: {} };
let worst = { ssim: 1, file: '' };
let totalIn = 0;
let totalOut = 0;
const rows = [];

function process1(src, outDir, base, targets, bucket, key) {
  const { w: native } = pngSize(src);
  const widths = widthsFor(native, targets);
  bucket[key] = widths;
  totalIn += fs.statSync(src).size;
  const top = widths[widths.length - 1];
  let quality = QUALITY_STEPS[0];
  let s = 0;
  const topFile = path.join(outDir, `${base}-${top}.webp`);
  for (const q of QUALITY_STEPS) {
    quality = q;
    encode(src, topFile, top, q);
    s = ssim(src, topFile, top);
    if (s >= MIN_SSIM) break;
  }
  let smallest = 0;
  let largest = 0;
  for (const w of widths) {
    const out = path.join(outDir, `${base}-${w}.webp`);
    if (w !== top) encode(src, out, w, quality);
    const size = fs.statSync(out).size;
    totalOut += size;
    if (!smallest) smallest = size;
    largest = size;
  }
  if (s < worst.ssim) worst = { ssim: s, file: base };
  rows.push({ base, native, widths, smallest, largest, ssim: s, quality });
  if (!(s >= MIN_SSIM)) console.error(`QUALITY WARNING: ${base} SSIM ${s} < ${MIN_SSIM} even at quality ${quality}`);
}

const destDir = path.join(ROOT, 'source-images/destinations');
const destOut = path.join(ROOT, 'public/images/destinations');
for (const file of fs.readdirSync(destDir).filter((f) => f.endsWith('.png')).sort()) {
  const slug = file.replace(/\.png$/, '');
  process1(path.join(destDir, file), destOut, slug, DESTINATION_WIDTHS, manifest.destinations, slug);
}
const brandOut = path.join(ROOT, 'public/images/brand');
for (const [name, targets] of Object.entries(BRAND_WIDTHS)) {
  process1(path.join(ROOT, 'source-images/brand', `${name}.png`), brandOut, name, targets, manifest.brand, name);
}

const js = `// Generated by scripts/optimize-images.cjs — do not edit by hand.
// Which responsive WebP widths exist for each photo (see src/utils/photoSources.js).
export const destinationImageWidths = ${JSON.stringify(manifest.destinations)};

export const brandImageWidths = ${JSON.stringify(manifest.brand)};
`;
fs.writeFileSync(path.join(ROOT, 'src/data/imageManifest.js'), js);

const kb = (n) => (n / 1024).toFixed(0);
console.log(`photos: ${rows.length} | originals ${(totalIn / 1048576).toFixed(1)} MB -> all WebP variants ${(totalOut / 1048576).toFixed(1)} MB`);
console.log(`worst SSIM vs original (largest variant): ${worst.ssim.toFixed(4)} (${worst.file}); quality used: ${[78, 84, 90].map((q) => q + ' x' + rows.filter((r) => r.quality === q).length).join(', ')}`);
console.log('largest single files served:');
rows.sort((a, b) => b.largest - a.largest).slice(0, 6).forEach((r) => console.log(`  ${r.base}: ${kb(r.largest)} KB at ${r.widths[r.widths.length - 1]}w (smallest ${kb(r.smallest)} KB at ${r.widths[0]}w)`));
